// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvGNPl-vSLvgdVmDJC-yrvL9V6dxpdpgI',
    appId: '1:1021290433498:web:227d48bbc17792b59b8ee3',
    messagingSenderId: '1021290433498',
    projectId: 'tej-rpg',
    authDomain: 'tej-rpg.firebaseapp.com',
    storageBucket: 'tej-rpg.firebasestorage.app',
    measurementId: 'G-94M2YD340L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVg7oACopAhwOKsygnIjfRUVTn3Jwcwj4',
    appId: '1:1021290433498:android:c6c234f9a73050889b8ee3',
    messagingSenderId: '1021290433498',
    projectId: 'tej-rpg',
    storageBucket: 'tej-rpg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJoo5BJ6kYI6gTVaCgwuTU9WRmu5DgI8',
    appId: '1:1021290433498:ios:a682ec5f767f12b79b8ee3',
    messagingSenderId: '1021290433498',
    projectId: 'tej-rpg',
    storageBucket: 'tej-rpg.firebasestorage.app',
    iosBundleId: 'com.example.rpg',
  );

}